### PR TITLE
✨ add identify API call

### PR DESCRIPTION
**Pull request by A-Tokyo**
### Description
– ✨ add identify API call (https://help.hotjar.com/hc/en-us/articles/360033640653-Identify-API-Reference#handling_user_ids)

Closes https://github.com/abdalla/react-hotjar/issues/29

### CODE REVIEW

**Comment by sidharth-ping** [comment]
Can this be merged soon? 

I would really like to track users

**Comment by A-Tokyo** [comment]
@abdalla Can you please review and release this? ✨ 

Thanks in advance!

**Review by abdalla — APPROVED** [review]

**Comment by sidharth-ping** [comment]
You saved me a bunch of work thank you so much!

**Comment by A-Tokyo** [comment]
@sidharth-ping My pleasure! ( :

**Comment by ivanicharts** [comment]
Hi. I'm sorry, but **identify** is not working for me. Does it for anyone else ?

I've checked the code and as I can see from implementation:

`module.exports = {
	hotjar: {
		initialize: function initialize(id, sv) {
			hotjar(id, sv);
		},
		identify: function identify(userId, properties) {
			hotjar('identify', userId, properties);
		}
	}
};`

**hotjar** - if function to import and initialize hotjar script on the page. And this function is also used in **identify**, which doesn't really make sense to me.

I might be wrong but it should be something like: 

`window.hj('identify', userId, properties);`

I can make a fix if that make sense :)

**Comment by sidharth-ping** [comment]
Yep it doesn't work I just checked.

**Comment by andrewda** [comment]
@ivanicharts @sidharth-ping #32 should resolve this issue, tested locally. You can give it a try with:

```bash
npm install --save "git://github.com/andrewda/react-hotjar.git#fix-identify"
```

Let me know if you run into any issues!

**Comment by miguelduarte42** [comment]
Is there a technical reason why this latest fix was never push to NPM?

**Comment by abdalla** [comment]
All approved PRs are there!

**Comment by miguelduarte42** [comment]
Thanks, you are right. For some reason I was getting an error when using identify, but it seems like it may have been a cache issue with v3

**Comment by abdalla** [comment]
I believe that the PR with the fix is not open yet.

**Pull request merged**
